base_frame_id: base_link
log_filename: mit-killian.clf
laser:
  fov: 180
  # resolution: 1.0
  range_min: 0.10
  range_max: 80.0
  ROS:
    tf: [0, 0, 0]
    topic: "/scan"
    frame_id: "laser"
    save_odom: false
odom:
  ROS:
    topic: "/odom"
    frame_id: "odom"
    publish_tf: true
