# Robot Operating System (ROS) Service - Set Filename through ROS Service
# (compatible with both 1 and 2 versions)
string filename
---
bool success   # indicate successful run of triggered service
string message # informational, e.g. for error messages
